[lint]
select = ["E", "F", "I", "B", "UP"]  # syntax, undefined names, errors, isort, bugbear, pyupgrade
ignore = [
    "E501",  # line length
    "B905",  # zip(strict=) not required
    "UP007", # PEP604 unions are disallowed (Python <3.10 compatibility)
    "UP045", # Optional[...] is required; do not replace with |
]

# Optional but recommended
exclude = ["freecad/build", "dist", ".venv"]
